name: .NET Core

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.5.0'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack --configuration Release --no-restore /p:PackageVersion=$GITVERSION_SEMVER --output ./output
    - name: Install NuGet
      uses: NuGet/setup-nuget@v1.0.5
      if: ${{ github.ref == 'refs/heads/master' }}
    - name: Publish to NuGet
      run: nuget push ./output/*.nupkg -ApiKey ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json
      if: ${{ github.ref == 'refs/heads/master' }}
